In [5]:
import numpy as np

In [2]:
a=np.array([1,1])
a

array([1, 1])

In [26]:
b=np.array([[1,3],[4,2]])
b

array([[1, 3],
       [4, 2]])

In [27]:
c=np.array([[1,3,4],[2,4,1],[2,3,1]])
c

array([[1, 3, 4],
       [2, 4, 1],
       [2, 3, 1]])

In [28]:
d=np.array([[8,1,2,4],[4,6,2,2],[1,5,3,4],[2,4,5,6]])
d

array([[8, 1, 2, 4],
       [4, 6, 2, 2],
       [1, 5, 3, 4],
       [2, 4, 5, 6]])

In [30]:
e=np.array([[1,4,1,5,1],[5,2,5,2,6],[3,2,3,1,3],[4,4,5,4,1],[1,5,3,5,9]])
e

array([[1, 4, 1, 5, 1],
       [5, 2, 5, 2, 6],
       [3, 2, 3, 1, 3],
       [4, 4, 5, 4, 1],
       [1, 5, 3, 5, 9]])

In [6]:
import numpy as na
from numpy import linalg as la

print(la.det(a)) #1-dimensional array given. Array must be at least two-dimensional

In [33]:
print(la.det(b))

-10.000000000000002


In [34]:
print(la.det(c))

-7.000000000000001


In [35]:
print(la.det(d))

-177.99999999999997


In [36]:
print(la.det(e))

-338.00000000000006


print(la.inv(a)) #1-dimensional array given. Array must be at least two-dimensional

In [79]:
print(la.inv(b))#inverse

[[-0.2  0.3]
 [ 0.4 -0.1]]


In [80]:
print(la.inv(c)) #inverse

[[-0.14285714 -1.28571429  1.85714286]
 [ 0.          1.         -1.        ]
 [ 0.28571429 -0.42857143  0.28571429]]


In [81]:
print(la.inv(d)) #inverse

[[ 0.07865169  0.12359551 -0.19101124  0.03370787]
 [-0.03370787  0.08988764  0.2247191  -0.15730337]
 [-0.31460674  0.50561798 -1.23595506  0.86516854]
 [ 0.25842697 -0.52247191  0.94382022 -0.46067416]]


In [82]:
print(la.inv(e)) #inverse

[[ 0.4408284   0.22485207  0.4408284  -0.3964497  -0.30177515]
 [ 0.04733728 -0.57988166  1.04733728 -0.08284024  0.04142012]
 [-0.53550296 -0.06508876 -0.53550296  0.56213018  0.21893491]
 [ 0.18047337  0.41420118 -0.81952663  0.0591716  -0.0295858 ]
 [ 0.00295858  0.0887574   0.00295858 -0.13017751  0.06508876]]


In [76]:
print(np.diag(a))  #diagonal
print(np.diag(b))
print(np.diag(c))
print(np.diag(d))
print(np.diag(e))

[[1 0]
 [0 1]]
[1 2]
[1 4 1]
[8 6 3 6]
[1 2 3 4 9]


In [75]:
print(la.matrix_rank(a)) #rank
print(la.matrix_rank(b))
print(la.matrix_rank(c))
print(la.matrix_rank(d))
print(la.matrix_rank(e))

1
2
3
4
5


print(np.trace(a)) #diag requires an array of at least two dimensions

In [84]:
print(np.trace(b)) #trace
print(np.trace(c))
print(np.trace(d))
print(np.trace(e))

3
6
23
19


x,y=la.eig(a) #eigenvalues and eigen vectors
print("roots:",x)  #1-dimensional array given. Array must be at least two-dimensional
print("vectors:",y)

In [73]:
x,y=la.eig(b) #eigenvalues and eigen vectors
print("roots:",x)
print("vectors:",y)

roots: [-2.  5.]
vectors: [[-0.70710678 -0.6       ]
 [ 0.70710678 -0.8       ]]


In [72]:
x,y=la.eig(c) #eigenvalues and eigen vectors
print("roots:",x)
print("vectors:",y)

roots: [ 7.         -1.61803399  0.61803399]
vectors: [[-0.63105474 -0.88513142  0.76169464]
 [-0.58898443  0.24464431 -0.55116742]
 [-0.50484379  0.39584281  0.3406402 ]]


In [71]:
x,y=la.eig(d) #eigenvalues and eigen vectors
print("roots:",x)
print("vectors:",y)

roots: [14.86875785+0.j         4.32032948+2.1988587j  4.32032948-2.1988587j
 -0.50941681+0.j       ]
vectors: [[-0.52478341+0.j         -0.58723586+0.j         -0.58723586-0.j
  -0.09278313+0.j        ]
 [-0.46244818+0.j         -0.07445615+0.46062079j -0.07445615-0.46062079j
   0.1303713 +0.j        ]
 [-0.4311263 +0.j          0.34351989-0.06147499j  0.34351989+0.06147499j
  -0.80708815+0.j        ]
 [-0.56997734+0.j          0.38706272-0.40722988j  0.38706272+0.40722988j
   0.56833383+0.j        ]]


In [70]:
x,y=la.eig(e) #eigenvalues and eigen vectors
print("roots:",x)
print("vectors:",y)

roots: [17.50988507+0.j          4.74226224+0.j         -2.5724648 +0.j
 -0.33984126+1.21113285j -0.33984126-1.21113285j]
vectors: [[ 0.29527261+0.j          0.47791282+0.j         -0.49794807+0.j
   0.1232926 -0.43612967j  0.1232926 +0.43612967j]
 [ 0.49373171+0.j         -0.14120283+0.j          0.78256234+0.j
  -0.53830857+0.j         -0.53830857-0.j        ]
 [ 0.291828  +0.j         -0.05587982+0.j          0.15393788+0.j
  -0.15441286+0.42511837j -0.15441286-0.42511837j]
 [ 0.39024117+0.j          0.60544206+0.j         -0.25619728+0.j
   0.52174413+0.08743593j  0.52174413-0.08743593j]
 [ 0.65695611+0.j         -0.61804405+0.j         -0.22429888+0.j
   0.06194494-0.12862976j  0.06194494+0.12862976j]]


In [7]:
import numpy as np
import pandas as pd

In [8]:
d1= pd.read_csv(r"C:\Users\settibathula nithin\Downloads\4_Drug200.csv")
d1

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [4]:
print(d1.describe())

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000


In [4]:
d1=d1.drop(['Sex','BP','Cholesterol','Drug'],axis=1)
d1

Age  Na_to_K
0     23   25.355
1     47   13.093
2     47   10.114
3     28    7.798
4     61   18.043
..   ...      ...
195   56   11.567
196   16   12.006
197   52    9.894
198   23   14.020
199   40   11.349

[200 rows x 2 columns]

In [19]:
print(d1.median())
print(d1.mode())
print(d1.mean())

Age        45.0000
Na_to_K    13.9365
dtype: float64
    Age  Na_to_K
0  47.0   12.006
1   NaN   18.295
Age        44.315000
Na_to_K    16.084485
dtype: float64


In [30]:
print(d1.count())
print(d1.cumsum())
print(d1.sum())
print(d1.min())
print(d1.max())

Age        200
Na_to_K    200
dtype: int64
      Age   Na_to_K
0      23    25.355
1      70    38.448
2     117    48.562
3     145    56.360
4     206    74.403
..    ...       ...
195  8732  3169.628
196  8748  3181.634
197  8800  3191.528
198  8823  3205.548
199  8863  3216.897

[200 rows x 2 columns]
Age        8863.000
Na_to_K    3216.897
dtype: float64
Age        15.000
Na_to_K     6.269
dtype: float64
Age        74.000
Na_to_K    38.247
dtype: float64


In [96]:
from scipy.stats import spearmanr
corr,_=spearmanr(d1["Age"],d1["Na_to_K"])
print(corr)

-0.047273882688479915


In [6]:
from scipy.stats import pearsonr
corr,_=pearsonr(d1["Age"],d1["Na_to_K"])
print(corr)

-0.06311949726772588


In [10]:
from numpy import cov
covarience=cov(d1["Age"],d1["Na_to_K"])
print(covarience)

[[273.71434673  -7.54375153]
 [ -7.54375153  52.18553348]]


In [56]:
d2= pd.read_csv(r"C:\Users\settibathula nithin\Downloads\3_Fitness.csv")
d2

SALESMAN    JAN    FEB    MAR    APR    MAY    JUN  TOTAL SALES  \
0             ANU   70.0   80.0   75.0   60.0   72.0   55.0        412.0   
1            BABU   30.0   48.0   35.0   45.0   25.0   37.0        220.0   
2         CHANDRU   65.0   54.0   49.0   54.0   35.0   65.0        322.0   
3           DAVID   85.0   71.0   68.0   77.0   88.0   73.0        462.0   
4        EINSTEIN   55.0   25.0   45.0   50.0   53.0   30.0        258.0   
5          FAROOK   35.0   45.0   15.0   45.0   45.0   25.0        210.0   
6         GOWTHAM   75.0   66.0   59.0   65.0   56.0   30.0        351.0   
7        HARSHITH   29.0   35.0   49.0   48.0   35.0   55.0        247.0   
8          INIYAN   35.0   35.0   50.0   59.0   67.0   73.0        319.0   
9            JOHN   77.0   85.0   77.0   68.0   56.0   25.0        388.0   
10  MONTHLY SALES  556.0  544.0  522.0  571.0  532.0  468.0          NaN   
11            NaN    NaN    NaN    NaN    NaN    NaN    NaN       3189.0   

    Unnamed: 8  Unnamed: 9  Unnamed: 10  \
0          NaN         NaN          NaN   
1          NaN         NaN          NaN   
2          NaN         NaN          NaN   
3          NaN         NaN          NaN   
4          NaN         NaN          NaN   
5          NaN         NaN          NaN   
6          NaN         NaN          NaN   
7          NaN         NaN          NaN   
8          NaN         NaN          NaN   
9          NaN         NaN          NaN   
10      3193.0         NaN          NaN   
11         NaN         NaN          NaN   

                                          Unnamed: 11  
0                                                 NaN  
1                     1. Individual Sales using Sum()  
2   2. Find the pattern trend using conditional fo...  
3   3. Analyze using Pivot table as column percentage  
4                              4. Insert Pivot charts  
5   5. Rank() - returns the rank of a given value ...  
6                                                 NaN  
7                                                  33  
8                                                 NaN  
9                                                 NaN  
10                                                NaN  
11                                                NaN

In [11]:
print(d2.describe())

              JAN         FEB         MAR         APR         MAY         JUN  \
count   11.000000   11.000000   11.000000   11.000000   11.000000   11.000000   
mean   101.090909   98.909091   94.909091  103.818182   96.727273   85.090909   
std    152.263886  148.884153  142.770763  155.277054  145.500578  128.347540   
min     29.000000   25.000000   15.000000   45.000000   25.000000   25.000000   
25%     35.000000   40.000000   47.000000   49.000000   40.000000   30.000000   
50%     65.000000   54.000000   50.000000   59.000000   56.000000   55.000000   
75%     76.000000   75.500000   71.500000   66.500000   69.500000   69.000000   
max    556.000000  544.000000  522.000000  571.000000  532.000000  468.000000   

       TOTAL SALES  Unnamed: 8  Unnamed: 9  Unnamed: 10  
count    11.000000         1.0         0.0          0.0  
mean    579.818182      3193.0         NaN          NaN  
std     869.142775         NaN         NaN          NaN  
min     210.000000      3193.0        

In [59]:
d2=d2.drop(['SALESMAN','Unnamed: 8','Unnamed: 9','Unnamed: 10','Unnamed: 11'],axis=1)
d2

JAN    FEB    MAR    APR    MAY    JUN  TOTAL SALES
0    70.0   80.0   75.0   60.0   72.0   55.0        412.0
1    30.0   48.0   35.0   45.0   25.0   37.0        220.0
2    65.0   54.0   49.0   54.0   35.0   65.0        322.0
3    85.0   71.0   68.0   77.0   88.0   73.0        462.0
4    55.0   25.0   45.0   50.0   53.0   30.0        258.0
5    35.0   45.0   15.0   45.0   45.0   25.0        210.0
6    75.0   66.0   59.0   65.0   56.0   30.0        351.0
7    29.0   35.0   49.0   48.0   35.0   55.0        247.0
8    35.0   35.0   50.0   59.0   67.0   73.0        319.0
9    77.0   85.0   77.0   68.0   56.0   25.0        388.0
10  556.0  544.0  522.0  571.0  532.0  468.0          NaN
11    NaN    NaN    NaN    NaN    NaN    NaN       3189.0

In [60]:
d2=d2.fillna(d2.median())
d2

JAN    FEB    MAR    APR    MAY    JUN  TOTAL SALES
0    70.0   80.0   75.0   60.0   72.0   55.0        412.0
1    30.0   48.0   35.0   45.0   25.0   37.0        220.0
2    65.0   54.0   49.0   54.0   35.0   65.0        322.0
3    85.0   71.0   68.0   77.0   88.0   73.0        462.0
4    55.0   25.0   45.0   50.0   53.0   30.0        258.0
5    35.0   45.0   15.0   45.0   45.0   25.0        210.0
6    75.0   66.0   59.0   65.0   56.0   30.0        351.0
7    29.0   35.0   49.0   48.0   35.0   55.0        247.0
8    35.0   35.0   50.0   59.0   67.0   73.0        319.0
9    77.0   85.0   77.0   68.0   56.0   25.0        388.0
10  556.0  544.0  522.0  571.0  532.0  468.0        322.0
11   65.0   54.0   50.0   59.0   56.0   55.0       3189.0

In [62]:
print(d2.median())
print(d2.mode())
print(d2.mean())

JAN             65.0
FEB             54.0
MAR             50.0
APR             59.0
MAY             56.0
JUN             55.0
TOTAL SALES    322.0
dtype: float64
    JAN   FEB   MAR   APR   MAY   JUN  TOTAL SALES
0  35.0  35.0  49.0  45.0  56.0  55.0        322.0
1  65.0  54.0  50.0  59.0   NaN   NaN          NaN
JAN             98.083333
FEB             95.166667
MAR             91.166667
APR            100.083333
MAY             93.333333
JUN             82.583333
TOTAL SALES    558.333333
dtype: float64


In [61]:
print(d2.count())
print(d2.cumsum())
print(d2.sum())
print(d2.min())
print(d2.max())

JAN            12
FEB            12
MAR            12
APR            12
MAY            12
JUN            12
TOTAL SALES    12
dtype: int64
       JAN     FEB     MAR     APR     MAY    JUN  TOTAL SALES
0     70.0    80.0    75.0    60.0    72.0   55.0        412.0
1    100.0   128.0   110.0   105.0    97.0   92.0        632.0
2    165.0   182.0   159.0   159.0   132.0  157.0        954.0
3    250.0   253.0   227.0   236.0   220.0  230.0       1416.0
4    305.0   278.0   272.0   286.0   273.0  260.0       1674.0
5    340.0   323.0   287.0   331.0   318.0  285.0       1884.0
6    415.0   389.0   346.0   396.0   374.0  315.0       2235.0
7    444.0   424.0   395.0   444.0   409.0  370.0       2482.0
8    479.0   459.0   445.0   503.0   476.0  443.0       2801.0
9    556.0   544.0   522.0   571.0   532.0  468.0       3189.0
10  1112.0  1088.0  1044.0  1142.0  1064.0  936.0       3511.0
11  1177.0  1142.0  1094.0  1201.0  1120.0  991.0       6700.0
JAN            1177.0
FEB            1142.

In [65]:
from scipy.stats import spearmanr 
corr,_=spearmanr(d2["JAN"],d2["TOTAL SALES"])
print(corr)

0.7188060310021683


In [64]:
from scipy.stats import pearsonr
corr,_=pearsonr(d2["JAN"],d2["TOTAL SALES"])
print(corr)

-0.059402675873807


In [90]:
from numpy import cov
covarience=cov(d2["JAN"],d2["TOTAL SALES"])
print(covarience)

[[ 21185.17424242  -7193.84848485]
 [ -7193.84848485 692274.78787879]]


In [67]:
d3= pd.read_csv(r"C:\Users\settibathula nithin\Downloads\1_2015.csv")
d3

Country                           Region  Happiness Rank  \
0    Switzerland                   Western Europe               1   
1        Iceland                   Western Europe               2   
2        Denmark                   Western Europe               3   
3         Norway                   Western Europe               4   
4         Canada                    North America               5   
..           ...                              ...             ...   
153       Rwanda               Sub-Saharan Africa             154   
154        Benin               Sub-Saharan Africa             155   
155        Syria  Middle East and Northern Africa             156   
156      Burundi               Sub-Saharan Africa             157   
157         Togo               Sub-Saharan Africa             158   

     Happiness Score  Standard Error  Economy (GDP per Capita)   Family  \
0              7.587         0.03411                   1.39651  1.34951   
1              7.561         0.04884                   1.30232  1.40223   
2              7.527         0.03328                   1.32548  1.36058   
3              7.522         0.03880                   1.45900  1.33095   
4              7.427         0.03553                   1.32629  1.32261   
..               ...             ...                       ...      ...   
153            3.465         0.03464                   0.22208  0.77370   
154            3.340         0.03656                   0.28665  0.35386   
155            3.006         0.05015                   0.66320  0.47489   
156            2.905         0.08658                   0.01530  0.41587   
157            2.839         0.06727                   0.20868  0.13995   

     Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                     0.94143  0.66557                        0.41978   
1                     0.94784  0.62877                        0.14145   
2                     0.87464  0.64938                        0.48357   
3                     0.88521  0.66973                        0.36503   
4                     0.90563  0.63297                        0.32957   
..                        ...      ...                            ...   
153                   0.42864  0.59201                        0.55191   
154                   0.31910  0.48450                        0.08010   
155                   0.72193  0.15684                        0.18906   
156                   0.22396  0.11850                        0.10062   
157                   0.28443  0.36453                        0.10731   

     Generosity  Dystopia Residual  
0       0.29678            2.51738  
1       0.43630            2.70201  
2       0.34139            2.49204  
3       0.34699            2.46531  
4       0.45811            2.45176  
..          ...                ...  
153     0.22628            0.67042  
154     0.18260            1.63328  
155     0.47179            0.32858  
156     0.19727            1.83302  
157     0.16681            1.56726  

[158 rows x 12 columns]

In [37]:
print(d3.describe())

       Happiness Rank  Happiness Score  Standard Error  \
count      158.000000       158.000000      158.000000   
mean        79.493671         5.375734        0.047885   
std         45.754363         1.145010        0.017146   
min          1.000000         2.839000        0.018480   
25%         40.250000         4.526000        0.037268   
50%         79.500000         5.232500        0.043940   
75%        118.750000         6.243750        0.052300   
max        158.000000         7.587000        0.136930   

       Economy (GDP per Capita)      Family  Health (Life Expectancy)  \
count                158.000000  158.000000                158.000000   
mean                   0.846137    0.991046                  0.630259   
std                    0.403121    0.272369                  0.247078   
min                    0.000000    0.000000                  0.000000   
25%                    0.545808    0.856823                  0.439185   
50%                    0.910245    1.02

In [68]:
d3=d3.drop(['Country','Region'],axis=1)
d3

Happiness Rank  Happiness Score  Standard Error  \
0                 1            7.587         0.03411   
1                 2            7.561         0.04884   
2                 3            7.527         0.03328   
3                 4            7.522         0.03880   
4                 5            7.427         0.03553   
..              ...              ...             ...   
153             154            3.465         0.03464   
154             155            3.340         0.03656   
155             156            3.006         0.05015   
156             157            2.905         0.08658   
157             158            2.839         0.06727   

     Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                     1.39651  1.34951                   0.94143  0.66557   
1                     1.30232  1.40223                   0.94784  0.62877   
2                     1.32548  1.36058                   0.87464  0.64938   
3                     1.45900  1.33095                   0.88521  0.66973   
4                     1.32629  1.32261                   0.90563  0.63297   
..                        ...      ...                       ...      ...   
153                   0.22208  0.77370                   0.42864  0.59201   
154                   0.28665  0.35386                   0.31910  0.48450   
155                   0.66320  0.47489                   0.72193  0.15684   
156                   0.01530  0.41587                   0.22396  0.11850   
157                   0.20868  0.13995                   0.28443  0.36453   

     Trust (Government Corruption)  Generosity  Dystopia Residual  
0                          0.41978     0.29678            2.51738  
1                          0.14145     0.43630            2.70201  
2                          0.48357     0.34139            2.49204  
3                          0.36503     0.34699            2.46531  
4                          0.32957     0.45811            2.45176  
..                             ...         ...                ...  
153                        0.55191     0.22628            0.67042  
154                        0.08010     0.18260            1.63328  
155                        0.18906     0.47179            0.32858  
156                        0.10062     0.19727            1.83302  
157                        0.10731     0.16681            1.56726  

[158 rows x 10 columns]

In [69]:
d3=d3.fillna(d3.median())
d3

Happiness Rank  Happiness Score  Standard Error  \
0                 1            7.587         0.03411   
1                 2            7.561         0.04884   
2                 3            7.527         0.03328   
3                 4            7.522         0.03880   
4                 5            7.427         0.03553   
..              ...              ...             ...   
153             154            3.465         0.03464   
154             155            3.340         0.03656   
155             156            3.006         0.05015   
156             157            2.905         0.08658   
157             158            2.839         0.06727   

     Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                     1.39651  1.34951                   0.94143  0.66557   
1                     1.30232  1.40223                   0.94784  0.62877   
2                     1.32548  1.36058                   0.87464  0.64938   
3                     1.45900  1.33095                   0.88521  0.66973   
4                     1.32629  1.32261                   0.90563  0.63297   
..                        ...      ...                       ...      ...   
153                   0.22208  0.77370                   0.42864  0.59201   
154                   0.28665  0.35386                   0.31910  0.48450   
155                   0.66320  0.47489                   0.72193  0.15684   
156                   0.01530  0.41587                   0.22396  0.11850   
157                   0.20868  0.13995                   0.28443  0.36453   

     Trust (Government Corruption)  Generosity  Dystopia Residual  
0                          0.41978     0.29678            2.51738  
1                          0.14145     0.43630            2.70201  
2                          0.48357     0.34139            2.49204  
3                          0.36503     0.34699            2.46531  
4                          0.32957     0.45811            2.45176  
..                             ...         ...                ...  
153                        0.55191     0.22628            0.67042  
154                        0.08010     0.18260            1.63328  
155                        0.18906     0.47179            0.32858  
156                        0.10062     0.19727            1.83302  
157                        0.10731     0.16681            1.56726  

[158 rows x 10 columns]

In [70]:
print(d3.median())
print(d3.mode())
print(d3.mean())

Happiness Rank                   79.500000
Happiness Score                   5.232500
Standard Error                    0.043940
Economy (GDP per Capita)          0.910245
Family                            1.029510
Health (Life Expectancy)          0.696705
Freedom                           0.435515
Trust (Government Corruption)     0.107220
Generosity                        0.216130
Dystopia Residual                 2.095415
dtype: float64
     Happiness Rank  Happiness Score  Standard Error  \
0              82.0            5.192         0.03751   
1               NaN              NaN         0.03780   
2               NaN              NaN         0.04394   
3               NaN              NaN         0.04934   
4               NaN              NaN         0.05051   
..              ...              ...             ...   
153             NaN              NaN             NaN   
154             NaN              NaN             NaN   
155             NaN              NaN             Na

In [40]:
print(d3.count())
print(d3.cumsum())
print(d3.sum())
print(d3.min())
print(d3.max())

Happiness Rank                   158
Happiness Score                  158
Standard Error                   158
Economy (GDP per Capita)         158
Family                           158
Health (Life Expectancy)         158
Freedom                          158
Trust (Government Corruption)    158
Generosity                       158
Dystopia Residual                158
dtype: int64
     Happiness Rank  Happiness Score  Standard Error  \
0                 1            7.587         0.03411   
1                 3           15.148         0.08295   
2                 6           22.675         0.11623   
3                10           30.197         0.15503   
4                15           37.624         0.19056   
..              ...              ...             ...   
153           11934          837.276         7.32523   
154           12089          840.616         7.36179   
155           12245          843.622         7.41194   
156           12402          846.527         7.49852   
1

In [74]:
from scipy.stats import pearsonr
corr,_=pearsonr(d3["Happiness Score"],d3["Dystopia Residual"])
print(corr)

0.5304735177821582


In [77]:
from scipy.stats import spearmanr
corr,_=spearmanr(d3["Happiness Score"],d3["Dystopia Residual"])
print(corr)

0.5324872196831733


In [93]:
from numpy import cov
covarience=cov(d3["Happiness Score"],d3["Dystopia Residual"])
print(covarience)

[[1.31104821 0.33622479]
 [0.33622479 0.30641737]]


In [27]:
d4= pd.read_csv(r"C:\Users\settibathula nithin\Downloads\7_Uber.csv")
d4

Unnamed: 0                            key  fare_amount  \
0         24238194    2015-05-07 19:52:06.0000003          7.5   
1         27835199    2009-07-17 20:04:56.0000002          7.7   
2         44984355   2009-08-24 21:45:00.00000061         12.9   
3         25894730    2009-06-26 08:22:21.0000001          5.3   
4         17610152  2014-08-28 17:47:00.000000188         16.0   
...            ...                            ...          ...   
199995    42598914   2012-10-28 10:49:00.00000053          3.0   
199996    16382965    2014-03-14 01:09:00.0000008          7.5   
199997    27804658   2009-06-29 00:42:00.00000078         30.9   
199998    20259894    2015-05-20 14:56:25.0000004         14.5   
199999    11951496   2010-05-15 04:08:00.00000076         14.1   

                pickup_datetime  pickup_longitude  pickup_latitude  \
0       2015-05-07 19:52:06 UTC        -73.999817        40.738354   
1       2009-07-17 20:04:56 UTC        -73.994355        40.728225   
2       2009-08-24 21:45:00 UTC        -74.005043        40.740770   
3       2009-06-26 08:22:21 UTC        -73.976124        40.790844   
4       2014-08-28 17:47:00 UTC        -73.925023        40.744085   
...                         ...               ...              ...   
199995  2012-10-28 10:49:00 UTC        -73.987042        40.739367   
199996  2014-03-14 01:09:00 UTC        -73.984722        40.736837   
199997  2009-06-29 00:42:00 UTC        -73.986017        40.756487   
199998  2015-05-20 14:56:25 UTC        -73.997124        40.725452   
199999  2010-05-15 04:08:00 UTC        -73.984395        40.720077   

        dropoff_longitude  dropoff_latitude  passenger_count  
0              -73.999512         40.723217                1  
1              -73.994710         40.750325                1  
2              -73.962565         40.772647                1  
3              -73.965316         40.803349                3  
4              -73.973082         40.761247                5  
...                   ...               ...              ...  
199995         -73.986525         40.740297                1  
199996         -74.006672         40.739620                1  
199997         -73.858957         40.692588                2  
199998         -73.983215         40.695415                1  
199999         -73.985508         40.768793                1  

[200000 rows x 9 columns]

In [47]:
print(d4.describe())

         Unnamed: 0    fare_amount  pickup_longitude  pickup_latitude  \
count  2.000000e+05  200000.000000     200000.000000    200000.000000   
mean   2.771250e+07      11.359955        -72.527638        39.935885   
std    1.601382e+07       9.901776         11.437787         7.720539   
min    1.000000e+00     -52.000000      -1340.648410       -74.015515   
25%    1.382535e+07       6.000000        -73.992065        40.734796   
50%    2.774550e+07       8.500000        -73.981823        40.752592   
75%    4.155530e+07      12.500000        -73.967154        40.767158   
max    5.542357e+07     499.000000         57.418457      1644.421482   

       dropoff_longitude  dropoff_latitude  passenger_count  
count      199999.000000     199999.000000    200000.000000  
mean          -72.525292         39.923890         1.684535  
std            13.117408          6.794829         1.385997  
min         -3356.666300       -881.985513         0.000000  
25%           -73.991407        

In [28]:
d4=d4.drop(['key','pickup_datetime'],axis=1)
d4

Unnamed: 0  fare_amount  pickup_longitude  pickup_latitude  \
0         24238194          7.5        -73.999817        40.738354   
1         27835199          7.7        -73.994355        40.728225   
2         44984355         12.9        -74.005043        40.740770   
3         25894730          5.3        -73.976124        40.790844   
4         17610152         16.0        -73.925023        40.744085   
...            ...          ...               ...              ...   
199995    42598914          3.0        -73.987042        40.739367   
199996    16382965          7.5        -73.984722        40.736837   
199997    27804658         30.9        -73.986017        40.756487   
199998    20259894         14.5        -73.997124        40.725452   
199999    11951496         14.1        -73.984395        40.720077   

        dropoff_longitude  dropoff_latitude  passenger_count  
0              -73.999512         40.723217                1  
1              -73.994710         40.750325                1  
2              -73.962565         40.772647                1  
3              -73.965316         40.803349                3  
4              -73.973082         40.761247                5  
...                   ...               ...              ...  
199995         -73.986525         40.740297                1  
199996         -74.006672         40.739620                1  
199997         -73.858957         40.692588                2  
199998         -73.983215         40.695415                1  
199999         -73.985508         40.768793                1  

[200000 rows x 7 columns]

In [29]:
d4=d4.fillna(d4.median())
d4

Unnamed: 0  fare_amount  pickup_longitude  pickup_latitude  \
0         24238194          7.5        -73.999817        40.738354   
1         27835199          7.7        -73.994355        40.728225   
2         44984355         12.9        -74.005043        40.740770   
3         25894730          5.3        -73.976124        40.790844   
4         17610152         16.0        -73.925023        40.744085   
...            ...          ...               ...              ...   
199995    42598914          3.0        -73.987042        40.739367   
199996    16382965          7.5        -73.984722        40.736837   
199997    27804658         30.9        -73.986017        40.756487   
199998    20259894         14.5        -73.997124        40.725452   
199999    11951496         14.1        -73.984395        40.720077   

        dropoff_longitude  dropoff_latitude  passenger_count  
0              -73.999512         40.723217                1  
1              -73.994710         40.750325                1  
2              -73.962565         40.772647                1  
3              -73.965316         40.803349                3  
4              -73.973082         40.761247                5  
...                   ...               ...              ...  
199995         -73.986525         40.740297                1  
199996         -74.006672         40.739620                1  
199997         -73.858957         40.692588                2  
199998         -73.983215         40.695415                1  
199999         -73.985508         40.768793                1  

[200000 rows x 7 columns]

In [30]:
print(d4.median())
print(d4.mode())
print(d4.mean())

Unnamed: 0           2.774550e+07
fare_amount          8.500000e+00
pickup_longitude    -7.398182e+01
pickup_latitude      4.075259e+01
dropoff_longitude   -7.398009e+01
dropoff_latitude     4.075304e+01
passenger_count      1.000000e+00
dtype: float64
        Unnamed: 0  fare_amount  pickup_longitude  pickup_latitude  \
0                1          6.5               0.0              0.0   
1               45          NaN               NaN              NaN   
2               48          NaN               NaN              NaN   
3              243          NaN               NaN              NaN   
4              335          NaN               NaN              NaN   
...            ...          ...               ...              ...   
199995    55421687          NaN               NaN              NaN   
199996    55421949          NaN               NaN              NaN   
199997    55422851          NaN               NaN              NaN   
199998    55422902          NaN               N

In [55]:
print(d4.count())
print(d4.cumsum())
print(d4.sum())
print(d4.min())
print(d4.max())

Unnamed: 0           200000
fare_amount          200000
pickup_longitude     200000
pickup_latitude      200000
dropoff_longitude    199999
dropoff_latitude     199999
passenger_count      200000
dtype: int64
           Unnamed: 0  fare_amount  pickup_longitude  pickup_latitude  \
0            24238194         7.50     -7.399982e+01     4.073835e+01   
1            52073393        15.20     -1.479942e+02     8.146658e+01   
2            97057748        28.10     -2.219992e+02     1.222073e+02   
3           122952478        33.40     -2.959753e+02     1.629982e+02   
4           140562630        49.40     -3.699004e+02     2.037423e+02   
...               ...          ...               ...              ...   
199995  5542424337457   2271924.05     -1.450523e+07     7.987014e+06   
199996  5542440720422   2271931.55     -1.450531e+07     7.987055e+06   
199997  5542468525080   2271962.45     -1.450538e+07     7.987096e+06   
199998  5542488784974   2271976.95     -1.450545e+07     7.98

In [78]:
from scipy.stats import pearsonr
corr,_=pearsonr(d4["fare_amount"],d4["passenger_count"])
print(corr)

0.010149925554529173


In [79]:
from scipy.stats import spearmanr
corr,_=spearmanr(d4["fare_amount"],d4["passenger_count"])
print(corr)

0.023295665466744574


In [94]:
from numpy import cov
covarience=cov(d4["fare_amount"],d4["passenger_count"])
print(covarience)

[[98.04517241  0.13929583]
 [ 0.13929583  1.92098644]]


In [82]:
d5= pd.read_csv(r"C:\Users\settibathula nithin\Downloads\6_salesworkload1.csv")
d5

MonthYear  Time index         Country  StoreID        City  Dept_ID  \
0      10.2016         1.0  United Kingdom  88253.0  London (I)      1.0   
1      10.2016         1.0  United Kingdom  88253.0  London (I)      2.0   
2      10.2016         1.0  United Kingdom  88253.0  London (I)      3.0   
3      10.2016         1.0  United Kingdom  88253.0  London (I)      4.0   
4      10.2016         1.0  United Kingdom  88253.0  London (I)      5.0   
...        ...         ...             ...      ...         ...      ...   
7653    6.2017         9.0          Sweden  29650.0  Gothenburg     12.0   
7654    6.2017         9.0          Sweden  29650.0  Gothenburg     16.0   
7655    6.2017         9.0          Sweden  29650.0  Gothenburg     11.0   
7656    6.2017         9.0          Sweden  29650.0  Gothenburg     17.0   
7657    6.2017         9.0          Sweden  29650.0  Gothenburg     18.0   

               Dept. Name  HoursOwn  HoursLease  Sales units    Turnover  \
0                     Dry  3184.764         0.0     398560.0   1226244.0   
1                  Frozen  1582.941         0.0      82725.0    387810.0   
2                   other    47.205         0.0     438400.0    654657.0   
3                    Fish  1623.852         0.0     309425.0    499434.0   
4     Fruits & Vegetables  1759.173         0.0     165515.0    329397.0   
...                   ...       ...         ...          ...         ...   
7653             Checkout  6322.323         0.0    3886530.0  14538825.0   
7654    Customer Services  4270.479         0.0        245.0         0.0   
7655             Delivery         0         0.0          0.0         0.0   
7656               others  2224.929         0.0        245.0         0.0   
7657                  all   39652.2         0.0    3886530.0  15056214.0   

      Customer Area (m2) Opening hours  
0          NaN    953.04        Type A  
1          NaN    720.48        Type A  
2          NaN    966.72        Type A  
3          NaN   1053.36        Type A  
4          NaN   1053.36        Type A  
...        ...       ...           ...  
7653       NaN       #NV        Type A  
7654       NaN       #NV        Type A  
7655       NaN       #NV        Type A  
7656       NaN       #NV        Type A  
7657       NaN       #NV        Type A  

[7658 rows x 14 columns]

In [69]:
print(d5.describe())

        Time index       StoreID      Dept_ID   HoursLease   Sales units  \
count  7650.000000   7650.000000  7650.000000  7650.000000  7.650000e+03   
mean      5.000000  61995.220000     9.470588    22.036078  1.076471e+06   
std       2.582158  29924.581631     5.337429   133.299513  1.728113e+06   
min       1.000000  12227.000000     1.000000     0.000000  0.000000e+00   
25%       3.000000  29650.000000     5.000000     0.000000  5.457125e+04   
50%       5.000000  75400.500000     9.000000     0.000000  2.932300e+05   
75%       7.000000  87703.000000    14.000000     0.000000  9.175075e+05   
max       9.000000  98422.000000    18.000000  3984.000000  1.124296e+07   

           Turnover  Customer  
count  7.650000e+03       0.0  
mean   3.721393e+06       NaN  
std    6.003380e+06       NaN  
min    0.000000e+00       NaN  
25%    2.726798e+05       NaN  
50%    9.319575e+05       NaN  
75%    3.264432e+06       NaN  
max    4.271739e+07       NaN  


In [83]:
d5=d5.drop(['Dept_ID','HoursOwn','Country','MonthYear','City','Dept. Name','Customer','Opening hours','Area (m2)'],axis=1)
d5

Time index  StoreID  HoursLease  Sales units    Turnover
0            1.0  88253.0         0.0     398560.0   1226244.0
1            1.0  88253.0         0.0      82725.0    387810.0
2            1.0  88253.0         0.0     438400.0    654657.0
3            1.0  88253.0         0.0     309425.0    499434.0
4            1.0  88253.0         0.0     165515.0    329397.0
...          ...      ...         ...          ...         ...
7653         9.0  29650.0         0.0    3886530.0  14538825.0
7654         9.0  29650.0         0.0        245.0         0.0
7655         9.0  29650.0         0.0          0.0         0.0
7656         9.0  29650.0         0.0        245.0         0.0
7657         9.0  29650.0         0.0    3886530.0  15056214.0

[7658 rows x 5 columns]

In [84]:
d5=d5.fillna(d5.median())
d5

Time index  StoreID  HoursLease  Sales units    Turnover
0            1.0  88253.0         0.0     398560.0   1226244.0
1            1.0  88253.0         0.0      82725.0    387810.0
2            1.0  88253.0         0.0     438400.0    654657.0
3            1.0  88253.0         0.0     309425.0    499434.0
4            1.0  88253.0         0.0     165515.0    329397.0
...          ...      ...         ...          ...         ...
7653         9.0  29650.0         0.0    3886530.0  14538825.0
7654         9.0  29650.0         0.0        245.0         0.0
7655         9.0  29650.0         0.0          0.0         0.0
7656         9.0  29650.0         0.0        245.0         0.0
7657         9.0  29650.0         0.0    3886530.0  15056214.0

[7658 rows x 5 columns]

In [85]:
print(d5.median())
print(d5.mode())
print(d5.mean())

Time index          5.0
StoreID         75400.5
HoursLease          0.0
Sales units    293230.0
Turnover       931957.5
dtype: float64
    Time index  StoreID  HoursLease  Sales units  Turnover
0          5.0  12227.0         0.0          0.0       0.0
1          NaN  15552.0         NaN          NaN       NaN
2          NaN  16927.0         NaN          NaN       NaN
3          NaN  17647.0         NaN          NaN       NaN
4          NaN  18808.0         NaN          NaN       NaN
5          NaN  19000.0         NaN          NaN       NaN
6          NaN  19340.0         NaN          NaN       NaN
7          NaN  19769.0         NaN          NaN       NaN
8          NaN  20166.0         NaN          NaN       NaN
9          NaN  20891.0         NaN          NaN       NaN
10         NaN  22117.0         NaN          NaN       NaN
11         NaN  23623.0         NaN          NaN       NaN
12         NaN  29650.0         NaN          NaN       NaN
13         NaN  32949.0         NaN    

In [55]:
print(d5.count())
print(d5.cumsum())
print(d5.sum())
print(d5.min())
print(d5.max())

Time index     7658
StoreID        7658
HoursLease     7658
Sales units    7658
Turnover       7658
dtype: int64
      Time index      StoreID  HoursLease   Sales units      Turnover
0            1.0      88253.0         0.0  3.985600e+05  1.226244e+06
1            2.0     176506.0         0.0  4.812850e+05  1.614054e+06
2            3.0     264759.0         0.0  9.196850e+05  2.268711e+06
3            4.0     353012.0         0.0  1.229110e+06  2.768145e+06
4            5.0     441265.0         0.0  1.394625e+06  3.097542e+06
...          ...          ...         ...           ...           ...
7653     38254.0  474748037.0    168576.0  8.233460e+09  2.846106e+10
7654     38263.0  474777687.0    168576.0  8.233460e+09  2.846106e+10
7655     38272.0  474807337.0    168576.0  8.233460e+09  2.846106e+10
7656     38281.0  474836987.0    168576.0  8.233460e+09  2.846106e+10
7657     38290.0  474866637.0    168576.0  8.237347e+09  2.847611e+10

[7658 rows x 5 columns]
Time index     3.82900

In [88]:
from scipy.stats import pearsonr
corr,_=pearsonr(d5["Time index"],d5["Turnover"])
print(corr)

-0.020335073817814017


In [89]:
from scipy.stats import spearmanr
corr,_=spearmanr(d5["Time index"],d5["Turnover"])
print(corr)

-0.01377200365334733


In [95]:
from numpy import cov
covarience=cov(d5["Time index"],d5["Turnover"])
print(covarience)

[[ 6.66057203e+00 -3.14933859e+05]
 [-3.14933859e+05  3.60110409e+13]]
